services:
  orgmgmt:
    image: 655289749580.dkr.ecr.ca-central-1.amazonaws.com/orgmgmt:latest
    container_name: orgmgmt
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Data Source=/data/app.db"
      AdminSettings__Email: "admin@orgmgmt.local"
      AdminSettings__Password: "Admin123!"
    volumes:
      - ./data:/data
      - ./keys:/root/.aspnet/DataProtection-Keys
